// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 11.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace CodedUITestProject7
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.HtmlControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public partial class UIMap
    {
        
        /// <summary>
        /// LoginMethod - Use 'LoginMethodParams' to pass parameters into this method.
        /// </summary>
        public void LoginMethod()
        {
            #region Variable Declarations
            HtmlDiv uIStikkymainPane = this.UIEduneeringInternetExWindow.UIEduneeringDocument.UIStikkymainPane;
            HtmlEdit uILOGINCTLT1Edit = this.UIEduneeringInternetExWindow.UIEduneeringDocument.UILOGINCTLT1Edit;
            HtmlEdit uILOGINCTLT2Edit = this.UIEduneeringInternetExWindow.UIEduneeringDocument.UILOGINCTLT2Edit;
            HtmlEdit uILOGINCTLT3Edit = this.UIEduneeringInternetExWindow.UIEduneeringDocument.UILOGINCTLT3Edit;
            HtmlHyperlink uIIAcceptHyperlink = this.UIEduneeringInternetExWindow.UIEduneeringDocument.UIIAcceptHyperlink;
            #endregion

            // Go to web page 'http://uat16.compliancewire.com/' using new browser instance
            this.UIBlankPageInternetExpWindow.LaunchUrl(new System.Uri(this.LoginMethodParams.UIBlankPageInternetExpWindowUrl));

            // Set flag to allow play back to continue if non-essential actions fail. (For example, if a mouse hover action fails.)
            Playback.PlaybackSettings.ContinueOnError = true;

            // Mouse hover 'stikkymain' pane at (1, 1)
            Mouse.Hover(uIStikkymainPane, new Point(1, 1));

            // Last mouse action was not recorded.

            // Reset flag to ensure that play back stops if there is an error.
            Playback.PlaybackSettings.ContinueOnError = false;

            // Type 'NSaxena' in 'LOGINCTL$T1' text box
            uILOGINCTLT1Edit.Text = this.LoginMethodParams.UILOGINCTLT1EditText;

            // Type '********' in 'LOGINCTL$T2' text box
            uILOGINCTLT2Edit.Password = this.LoginMethodParams.UILOGINCTLT2EditPassword;

            // Type 'edu' in 'LOGINCTL$T3' text box
            uILOGINCTLT3Edit.Text = this.LoginMethodParams.UILOGINCTLT3EditText;

            // Click 'I Accept' link
            Mouse.Click(uIIAcceptHyperlink, new Point(48, 13));
        }
        
        /// <summary>
        /// LoginAssertMethod - Use 'LoginAssertMethodExpectedValues' to pass parameters into this method.
        /// </summary>
        public void LoginAssertMethod()
        {
            #region Variable Declarations
            HtmlHyperlink uIWelcomeNarendraHyperlink = this.UIUat16EduneeringInterWindow.UIUat16EduneeringDocument.UIWelcomeNarendraPane.UIWelcomeNarendraHyperlink;
            #endregion

            // Verify that the 'InnerText' property of 'Welcome, Narendra' link equals 'Welcome, Narendra'
            Assert.AreEqual(this.LoginAssertMethodExpectedValues.UIWelcomeNarendraHyperlinkInnerText, uIWelcomeNarendraHyperlink.InnerText, "Login Unsuccessful !");
        }
        
        #region Properties
        public virtual LoginMethodParams LoginMethodParams
        {
            get
            {
                if ((this.mLoginMethodParams == null))
                {
                    this.mLoginMethodParams = new LoginMethodParams();
                }
                return this.mLoginMethodParams;
            }
        }
        
        public virtual LoginAssertMethodExpectedValues LoginAssertMethodExpectedValues
        {
            get
            {
                if ((this.mLoginAssertMethodExpectedValues == null))
                {
                    this.mLoginAssertMethodExpectedValues = new LoginAssertMethodExpectedValues();
                }
                return this.mLoginAssertMethodExpectedValues;
            }
        }
        
        public UIBlankPageInternetExpWindow UIBlankPageInternetExpWindow
        {
            get
            {
                if ((this.mUIBlankPageInternetExpWindow == null))
                {
                    this.mUIBlankPageInternetExpWindow = new UIBlankPageInternetExpWindow();
                }
                return this.mUIBlankPageInternetExpWindow;
            }
        }
        
        public UIEduneeringInternetExWindow UIEduneeringInternetExWindow
        {
            get
            {
                if ((this.mUIEduneeringInternetExWindow == null))
                {
                    this.mUIEduneeringInternetExWindow = new UIEduneeringInternetExWindow();
                }
                return this.mUIEduneeringInternetExWindow;
            }
        }
        
        public UIUat16EduneeringInterWindow UIUat16EduneeringInterWindow
        {
            get
            {
                if ((this.mUIUat16EduneeringInterWindow == null))
                {
                    this.mUIUat16EduneeringInterWindow = new UIUat16EduneeringInterWindow();
                }
                return this.mUIUat16EduneeringInterWindow;
            }
        }
        #endregion
        
        #region Fields
        private LoginMethodParams mLoginMethodParams;
        
        private LoginAssertMethodExpectedValues mLoginAssertMethodExpectedValues;
        
        private UIBlankPageInternetExpWindow mUIBlankPageInternetExpWindow;
        
        private UIEduneeringInternetExWindow mUIEduneeringInternetExWindow;
        
        private UIUat16EduneeringInterWindow mUIUat16EduneeringInterWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'LoginMethod'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class LoginMethodParams
    {
        
        #region Fields
        /// <summary>
        /// Go to web page 'http://uat16.compliancewire.com/' using new browser instance
        /// </summary>
        public string UIBlankPageInternetExpWindowUrl = "http://uat16.compliancewire.com/";
        
        /// <summary>
        /// Type 'NSaxena' in 'LOGINCTL$T1' text box
        /// </summary>
        public string UILOGINCTLT1EditText = "NSaxena";
        
        /// <summary>
        /// Type '********' in 'LOGINCTL$T2' text box
        /// </summary>
        public string UILOGINCTLT2EditPassword = "GY/4yFKgxsVCEilbOvhsUw==";
        
        /// <summary>
        /// Type 'edu' in 'LOGINCTL$T3' text box
        /// </summary>
        public string UILOGINCTLT3EditText = "edu";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'LoginAssertMethod'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class LoginAssertMethodExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Verify that the 'InnerText' property of 'Welcome, Narendra' link equals 'Welcome, Narendra'
        /// </summary>
        public string UIWelcomeNarendraHyperlinkInnerText = "Welcome, Narendra";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UIBlankPageInternetExpWindow : BrowserWindow
    {
        
        public UIBlankPageInternetExpWindow()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "Blank Page";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("Blank Page");
            this.WindowTitles.Add("This page can’t be displayed");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UIEduneeringInternetExWindow : BrowserWindow
    {
        
        public UIEduneeringInternetExWindow()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = ". Eduneering";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add(". Eduneering");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UIEduneeringDocument UIEduneeringDocument
        {
            get
            {
                if ((this.mUIEduneeringDocument == null))
                {
                    this.mUIEduneeringDocument = new UIEduneeringDocument(this);
                }
                return this.mUIEduneeringDocument;
            }
        }
        #endregion
        
        #region Fields
        private UIEduneeringDocument mUIEduneeringDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UIEduneeringDocument : HtmlDocument
    {
        
        public UIEduneeringDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = ". Eduneering";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/Net/Secure/login.aspx";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "https://uat16.compliancewire.com/Net/Secure/login.aspx";
            this.WindowTitles.Add(". Eduneering");
            #endregion
        }
        
        #region Properties
        public HtmlDiv UIStikkymainPane
        {
            get
            {
                if ((this.mUIStikkymainPane == null))
                {
                    this.mUIStikkymainPane = new HtmlDiv(this);
                    #region Search Criteria
                    this.mUIStikkymainPane.SearchProperties[HtmlDiv.PropertyNames.Id] = "stikkymain";
                    this.mUIStikkymainPane.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUIStikkymainPane.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Login System Status\r\n\r\n UAT16 \r\n   \r\n\r\n\r";
                    this.mUIStikkymainPane.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mUIStikkymainPane.FilterProperties[HtmlDiv.PropertyNames.Class] = null;
                    this.mUIStikkymainPane.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "id=\"stikkymain\"";
                    this.mUIStikkymainPane.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "2";
                    this.mUIStikkymainPane.WindowTitles.Add(". Eduneering");
                    #endregion
                }
                return this.mUIStikkymainPane;
            }
        }
        
        public HtmlEdit UILOGINCTLT1Edit
        {
            get
            {
                if ((this.mUILOGINCTLT1Edit == null))
                {
                    this.mUILOGINCTLT1Edit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUILOGINCTLT1Edit.SearchProperties[HtmlEdit.PropertyNames.Id] = "LOGINCTL_T1";
                    this.mUILOGINCTLT1Edit.SearchProperties[HtmlEdit.PropertyNames.Name] = "LOGINCTL$T1";
                    this.mUILOGINCTLT1Edit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = null;
                    this.mUILOGINCTLT1Edit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUILOGINCTLT1Edit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUILOGINCTLT1Edit.FilterProperties[HtmlEdit.PropertyNames.Class] = null;
                    this.mUILOGINCTLT1Edit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"LOGINCTL$T1\" tabindex=\"1\" id=\"LOGI";
                    this.mUILOGINCTLT1Edit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "6";
                    this.mUILOGINCTLT1Edit.WindowTitles.Add(". Eduneering");
                    #endregion
                }
                return this.mUILOGINCTLT1Edit;
            }
        }
        
        public HtmlEdit UILOGINCTLT2Edit
        {
            get
            {
                if ((this.mUILOGINCTLT2Edit == null))
                {
                    this.mUILOGINCTLT2Edit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUILOGINCTLT2Edit.SearchProperties[HtmlEdit.PropertyNames.Id] = "LOGINCTL_T2";
                    this.mUILOGINCTLT2Edit.SearchProperties[HtmlEdit.PropertyNames.Name] = "LOGINCTL$T2";
                    this.mUILOGINCTLT2Edit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = null;
                    this.mUILOGINCTLT2Edit.FilterProperties[HtmlEdit.PropertyNames.Type] = "PASSWORD";
                    this.mUILOGINCTLT2Edit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUILOGINCTLT2Edit.FilterProperties[HtmlEdit.PropertyNames.Class] = null;
                    this.mUILOGINCTLT2Edit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"LOGINCTL$T2\" tabindex=\"2\" id=\"LOGI";
                    this.mUILOGINCTLT2Edit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "8";
                    this.mUILOGINCTLT2Edit.WindowTitles.Add(". Eduneering");
                    #endregion
                }
                return this.mUILOGINCTLT2Edit;
            }
        }
        
        public HtmlEdit UILOGINCTLT3Edit
        {
            get
            {
                if ((this.mUILOGINCTLT3Edit == null))
                {
                    this.mUILOGINCTLT3Edit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUILOGINCTLT3Edit.SearchProperties[HtmlEdit.PropertyNames.Id] = "LOGINCTL_T3";
                    this.mUILOGINCTLT3Edit.SearchProperties[HtmlEdit.PropertyNames.Name] = "LOGINCTL$T3";
                    this.mUILOGINCTLT3Edit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = null;
                    this.mUILOGINCTLT3Edit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUILOGINCTLT3Edit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUILOGINCTLT3Edit.FilterProperties[HtmlEdit.PropertyNames.Class] = null;
                    this.mUILOGINCTLT3Edit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"LOGINCTL$T3\" tabindex=\"3\" id=\"LOGI";
                    this.mUILOGINCTLT3Edit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "10";
                    this.mUILOGINCTLT3Edit.WindowTitles.Add(". Eduneering");
                    #endregion
                }
                return this.mUILOGINCTLT3Edit;
            }
        }
        
        public HtmlHyperlink UIIAcceptHyperlink
        {
            get
            {
                if ((this.mUIIAcceptHyperlink == null))
                {
                    this.mUIIAcceptHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUIIAcceptHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = "lnkAccept";
                    this.mUIIAcceptHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUIIAcceptHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUIIAcceptHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "I Accept";
                    this.mUIIAcceptHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/Net/Secure/login.aspx";
                    this.mUIIAcceptHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUIIAcceptHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "https://uat16.compliancewire.com/Net/Secure/login.aspx#";
                    this.mUIIAcceptHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = "button";
                    this.mUIIAcceptHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "class=\"button\" id=\"lnkAccept\" onclick=\"j";
                    this.mUIIAcceptHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "6";
                    this.mUIIAcceptHyperlink.WindowTitles.Add(". Eduneering");
                    #endregion
                }
                return this.mUIIAcceptHyperlink;
            }
        }
        #endregion
        
        #region Fields
        private HtmlDiv mUIStikkymainPane;
        
        private HtmlEdit mUILOGINCTLT1Edit;
        
        private HtmlEdit mUILOGINCTLT2Edit;
        
        private HtmlEdit mUILOGINCTLT3Edit;
        
        private HtmlHyperlink mUIIAcceptHyperlink;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UIUat16EduneeringInterWindow : BrowserWindow
    {
        
        public UIUat16EduneeringInterWindow()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "uat16. Eduneering";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("uat16. Eduneering");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UIUat16EduneeringDocument UIUat16EduneeringDocument
        {
            get
            {
                if ((this.mUIUat16EduneeringDocument == null))
                {
                    this.mUIUat16EduneeringDocument = new UIUat16EduneeringDocument(this);
                }
                return this.mUIUat16EduneeringDocument;
            }
        }
        #endregion
        
        #region Fields
        private UIUat16EduneeringDocument mUIUat16EduneeringDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UIUat16EduneeringDocument : HtmlDocument
    {
        
        public UIUat16EduneeringDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = "pageBody";
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "uat16. Eduneering";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/Net/KnowledgeCenter.aspx";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "https://uat16.compliancewire.com/Net/KnowledgeCenter.aspx?MenuType=1";
            this.WindowTitles.Add("uat16. Eduneering");
            #endregion
        }
        
        #region Properties
        public UIWelcomeNarendraPane UIWelcomeNarendraPane
        {
            get
            {
                if ((this.mUIWelcomeNarendraPane == null))
                {
                    this.mUIWelcomeNarendraPane = new UIWelcomeNarendraPane(this);
                }
                return this.mUIWelcomeNarendraPane;
            }
        }
        #endregion
        
        #region Fields
        private UIWelcomeNarendraPane mUIWelcomeNarendraPane;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UIWelcomeNarendraPane : HtmlSpan
    {
        
        public UIWelcomeNarendraPane(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDiv.PropertyNames.Id] = "ucLeftMenu_lblWelcomeText";
            this.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Welcome, Narendra";
            this.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.Class] = "welcomeText";
            this.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=\"welcomeText\" id=\"ucLeftMenu_lblWelcomeText\"";
            this.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "3";
            this.WindowTitles.Add("uat16. Eduneering");
            #endregion
        }
        
        #region Properties
        public HtmlHyperlink UIWelcomeNarendraHyperlink
        {
            get
            {
                if ((this.mUIWelcomeNarendraHyperlink == null))
                {
                    this.mUIWelcomeNarendraHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUIWelcomeNarendraHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUIWelcomeNarendraHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUIWelcomeNarendraHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUIWelcomeNarendraHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Welcome, Narendra";
                    this.mUIWelcomeNarendraHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "ShowSettings();";
                    this.mUIWelcomeNarendraHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = "Saxena, Narendra ";
                    this.mUIWelcomeNarendraHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "javascript:ShowSettings();";
                    this.mUIWelcomeNarendraHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = null;
                    this.mUIWelcomeNarendraHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "title=\"Saxena, Narendra \" href=\"javascri";
                    this.mUIWelcomeNarendraHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "1";
                    this.mUIWelcomeNarendraHyperlink.WindowTitles.Add("uat16. Eduneering");
                    #endregion
                }
                return this.mUIWelcomeNarendraHyperlink;
            }
        }
        #endregion
        
        #region Fields
        private HtmlHyperlink mUIWelcomeNarendraHyperlink;
        #endregion
    }
}
